manifest_id: manual_je100c_eu_pl
pages:
  - {type: rst_include, lang: pl, file: templates/page_je100c_eu-pl/safety_pl.rst}
  - {type: rst_include, lang: pl, file: templates/page_je100c_eu-pl/01_user_maintenance_instructions.rst}
  - {type: rst_include, lang: pl, file: templates/page_je100c_eu-pl/symbol_meaning_pl.rst}
  - {type: rst_include, lang: pl, file: templates/page_je100c_eu-pl/02_whats_in_the_box.rst}
  - {type: rst_include, lang: pl, file: templates/page_je100c_eu-pl/03_product_overview.rst}
  - {type: rst_include, lang: pl, file: templates/page_je100c_eu-pl/lcd_display_pl.rst}
  - {type: rst_include, lang: pl, file: templates/page_je100c_eu-pl/operation_pl.rst}
  - {type: rst_include, lang: pl, file: templates/page_je100c_eu-pl/charging_pl.rst}
  - {type: rst_include, lang: pl, file: templates/page_je100c_eu-pl/storage_pl.rst}
  - {type: rst_include, lang: pl, file: templates/page_je100c_eu-pl/spec_pl.rst}
  - {type: rst_include, lang: pl, file: templates/page_je100c_eu-pl/warranty_pl.rst}
