manifest_id: manual_je100c_kr_ko
pages:
  - {type: rst_include, lang: ko, file: templates/page_je100c_kr-ko/safety_ko.rst}
  - {type: rst_include, lang: ko, file: templates/page_je100c_kr-ko/symbols_ko.rst}
  - {type: rst_include, lang: ko, file: templates/page_je100c_kr-ko/02_whats_in_the_box.rst}
  - {type: rst_include, lang: ko, file: templates/page_je100c_kr-ko/product_overview_ko.rst}
  - {type: rst_include, lang: ko, file: templates/page_je100c_kr-ko/lcd_display_ko.rst}
  - {type: rst_include, lang: ko, file: templates/page_je100c_kr-ko/operation_ko.rst}
  - {type: rst_include, lang: ko, file: templates/page_je100c_kr-ko/07_charging.rst}
  - {type: rst_include, lang: ko, file: templates/page_je100c_kr-ko/storage_ko.rst}
  - {type: rst_include, lang: ko, file: templates/page_je100c_kr-ko/specifications_ko.rst}
  - {type: rst_include, lang: ko, file: templates/page_je100c_kr-ko/warranty_ko.rst}
