manifest_id: manual_pt_br
pages:
  - type: rst_include
    lang: pt-BR
    file: templates/page_pt-br/00_preface.rst
  - type: rst_include
    lang: pt-BR
    file: templates/page_pt-br/safety_pt-BR.rst
  - type: rst_include
    lang: pt-BR
    file: templates/page_pt-br/01_user_maintenance_instructions.rst
  - type: rst_include
    lang: pt-BR
    file: templates/page_pt-br/01_meaning_of_symbols.rst
  - type: rst_include
    lang: pt-BR
    file: templates/page_pt-br/01_fcc.rst
  - type: rst_include
    lang: pt-BR
    file: templates/page_pt-br/02_whats_in_the_box.rst
  - type: rst_include
    lang: pt-BR
    file: templates/page_pt-br/03_product_overview_placeholder.rst
  - type: rst_include
    lang: pt-BR
    file: templates/page_pt-br/04_lcd_display_placeholder.rst
  - type: rst_include
    lang: pt-BR
    file: templates/page_pt-br/05_operation_guide_placeholder.rst
  - type: rst_include
    lang: pt-BR
    file: templates/page_pt-br/06_ups_mode.rst
  - type: rst_include
    lang: pt-BR
    file: templates/page_pt-br/charging.rst
  - type: rst_include
    lang: pt-BR
    file: templates/page_pt-br/09_storage_and_maintenance.rst
  - type: rst_include
    lang: pt-BR
    file: templates/page_pt-br/10_troubleshooting.rst
  - type: rst_include
    lang: pt-BR
    file: templates/page_pt-br/spec_pt-BR.rst
  - type: rst_include
    lang: pt-BR
    file: templates/page_pt-br/11_warranty.rst
  - type: rst_include
    lang: pt-BR
    file: templates/page_pt-br/12_app_setup_placeholder.rst
