extends: config-bases/us-single-language-base.yaml

build:
  family_id: us-fr
  languages: [fr]
  include_lang_in_output_path: true
  word_reference_doc: docs/templates/word_template/template.docx
  word_title_copy_key: word_title

paths:
  page_manifest: docs/manifests/manual_us-single-fr.yaml
