extends: config-bases/eu-single-language-base.yaml

build:
  family_id: eu-en
  languages: [en]
  word_reference_doc: docs/templates/word_template/reference_en.docx
  word_title: "|PRODUCT_NAME| User Manual"
  rst_substitutions:
    MANUAL_LANGUAGE_SCOPE: English / French / Spanish / German / Italian

paths:
  page_manifest: docs/manifests/manual_eu-en.yaml
