extends: config.eu-en.yaml

build:
  family_id: pt-br-en
  default_model: JE-1500D
  default_region: pt-BR
  targets:
    - model: JE-1500D
      region: pt-BR
  languages: [en]
  include_lang_in_output_path: true
  word_reference_doc: docs/templates/word_template/reference_en.docx
  word_title: "|PRODUCT_NAME| User Manual"
  rst_substitutions:
    MANUAL_LANGUAGE_SCOPE: English
    WARRANTY_EMAIL: hello@jackery.com

paths:
  page_manifest: docs/manifests/manual_pt-br-en.yaml
