from __future__ import annotations

import unittest
from pathlib import Path

from tools.config_pages import parse_config_pages_or_raise
from tools.skeleton_resolve import (
    emit_manifest_yaml,
    load_blueprint,
    load_region_profile,
    load_slot_templates,
    resolve_plan,
)

ROOT = Path(__file__).resolve().parents[1]
SKELETON_DIR = ROOT / "docs" / "manifests" / "skeletons" / "bp-intl"
REGION_PROFILE = ROOT / "docs" / "manifests" / "region_profiles" / "us.yaml"
COMMITTED = ROOT / "docs" / "manifests" / "manual_bp_us.yaml"


def _resolved_text() -> str:
    blueprint = load_blueprint(SKELETON_DIR / "blueprint.yaml")
    slot_templates = load_slot_templates(SKELETON_DIR / "slot_templates.yaml", blueprint)
    profile = load_region_profile(REGION_PROFILE, blueprint)
    plan = resolve_plan(blueprint, slot_templates, profile, manifest_id="manual_bp_us")
    header = [
        "Resolved Manifest — generated by tools/skeleton_resolve.py. Do not hand-edit.",
        f"Sources: {SKELETON_DIR.relative_to(ROOT).as_posix()}/blueprint.yaml + slot_templates.yaml",
        f"         + {REGION_PROFILE.relative_to(ROOT).as_posix()}",
        "Regenerate: python tools/skeleton_resolve.py emit "
        f"--skeleton-dir {SKELETON_DIR.relative_to(ROOT).as_posix()} "
        f"--region-profile {REGION_PROFILE.relative_to(ROOT).as_posix()} "
        "--manifest-id manual_bp_us --out <this file>",
    ]
    return emit_manifest_yaml(plan, header=header)


class SkeletonResolveTests(unittest.TestCase):
    def test_committed_manifest_is_byte_identical_to_resolver_output(self) -> None:
        # Generate-then-verify: YAML stays the compatibility surface; the
        # committed file must be exactly what the carriers resolve to.
        self.assertEqual(_resolved_text(), COMMITTED.read_text(encoding="utf-8"))

    def test_blueprint_excludes_host_only_slots(self) -> None:
        blueprint = load_blueprint(SKELETON_DIR / "blueprint.yaml")
        slot_ids = {slot["slot_id"] for slot in blueprint["slots"]}
        # 0/7 in the battery-pack corpus: these are host-line slots and their
        # presence here would print chapters the shipped books do not have.
        self.assertNotIn("app_setup", slot_ids)
        self.assertNotIn("user_maintenance_instructions", slot_ids)

    def test_capability_slots_carry_annotations_for_the_runtime_gate(self) -> None:
        # The resolver stamps capability annotations; the actual drop happens
        # at build time in filter_pages_by_capability via the all-FALSE row.
        blueprint = load_blueprint(SKELETON_DIR / "blueprint.yaml")
        slot_templates = load_slot_templates(SKELETON_DIR / "slot_templates.yaml", blueprint)
        profile = load_region_profile(REGION_PROFILE, blueprint)
        plan = resolve_plan(blueprint, slot_templates, profile, manifest_id="manual_bp_us")
        gated = {
            entry["slot_id"]: entry.get("capability")
            for entry in plan["pages"]
            if entry.get("capability")
        }
        for lang in profile["language_set"]:
            self.assertEqual("UPS功能", gated.get(f"ups_mode_{lang}"))
            self.assertEqual("加电包扩容", gated.get(f"extra_battery_{lang}"))

    def test_emitted_pages_parse_cleanly_with_unique_slot_ids(self) -> None:
        import yaml

        data = yaml.safe_load(COMMITTED.read_text(encoding="utf-8"))
        pages = parse_config_pages_or_raise(
            data["pages"], default_languages=["en", "fr", "es"], model="JBP-2000B"
        )
        slot_ids = [getattr(page, "slot_id", None) for page in pages]
        self.assertTrue(all(slot_ids), "every emitted entry must carry a slot_id")
        self.assertEqual(len(slot_ids), len(set(slot_ids)))

    def test_body_slots_expand_once_per_language_in_order(self) -> None:
        blueprint = load_blueprint(SKELETON_DIR / "blueprint.yaml")
        slot_templates = load_slot_templates(SKELETON_DIR / "slot_templates.yaml", blueprint)
        profile = load_region_profile(REGION_PROFILE, blueprint)
        plan = resolve_plan(blueprint, slot_templates, profile, manifest_id="manual_bp_us")
        body_slots = [s["slot_id"] for s in blueprint["slots"] if s["block"] == "body"]
        for lang in profile["language_set"]:
            suffix = f"_{lang}"
            expanded = [
                e["slot_id"][: -len(suffix)]
                for e in plan["pages"]
                if e["slot_id"].endswith(suffix)
            ]
            for slot_id in body_slots:
                self.assertIn(slot_id, expanded, f"{slot_id} missing for {lang}")
            # blueprint order is preserved inside each language block
            positions = [expanded.index(s) for s in body_slots]
            self.assertEqual(positions, sorted(positions))


if __name__ == "__main__":
    unittest.main()
