// Generic change applier for PDF-compatible .ai manuals. ASCII-only by design (see ai-manual-pagenum-fix skill).
// Generated by spec2jsx.py. Operates on app.activeDocument. Returns a text log; first line "OK=n FAIL=m DRY=bool".
var T = __DATA__;
var DRY = __DRY__;
var EXPECT_AB = __ARTBOARDS__;
function S(a) { var s = ""; for (var i = 0; i < a.length; i++) s += String.fromCharCode(a[i]); return s; }
function main() {
  app.userInteractionLevel = UserInteractionLevel.DONTDISPLAYALERTS;
  var doc = app.activeDocument, log = [], ok = 0, fail = 0;
  if (doc.artboards.length !== EXPECT_AB) return "ABORT artboards=" + doc.artboards.length + " expected=" + EXPECT_AB;
  var rectOf = {}, bk = {};
  for (var i = 0; i < T.length; i++) { var a = T[i].ab; if (!rectOf[a]) { rectOf[a] = doc.artboards[a].artboardRect; bk[a] = []; } }
  // one pass over all text frames, bucket by artboard (never scan per target)
  var n = doc.textFrames.length;
  for (var t = 0; t < n; t++) {
    var tf = doc.textFrames[t], gb;
    try { gb = tf.geometricBounds; } catch (e) { continue; }
    var cx = (gb[0] + gb[2]) / 2, cy = (gb[1] + gb[3]) / 2;
    for (var a in rectOf) { var r = rectOf[a];
      if (cx >= r[0] - 2 && cx <= r[2] + 2 && cy <= r[1] + 2 && cy >= r[3] - 2) { bk[a].push({tf: tf, gb: gb}); break; } }
  }
  var used = [];
  for (var i = 0; i < T.length; i++) {
    var g = T[i];
    if (g.op === "delete_artboard") continue;
    var r = rectOf[g.ab], ax = g.cx + r[0], ay = r[1] - g.cy, oldS = S(g.old), newS = S(g.new);
    // candidates: frames whose bounds contain the span centre (3pt slack) and whose contents match
    var best = null, bestArea = 1e12, nMatch = 0;
    for (var b = 0; b < bk[g.ab].length; b++) {
      var e = bk[g.ab][b], q = e.gb;
      if (ax < q[0] - 3 || ax > q[2] + 3 || ay > q[1] + 3 || ay < q[3] - 3) continue;
      var c; try { c = e.tf.contents; } catch (x) { continue; }
      var hit = (g.op === "set") ? (c === oldS) : (c.indexOf(oldS) >= 0 && c.indexOf(oldS) === c.lastIndexOf(oldS));
      if (!hit) continue;
      nMatch++;
      var area = (q[2] - q[0]) * (q[1] - q[3]);
      if (area < bestArea) { bestArea = area; best = e.tf; }
    }
    if (!best) { fail++; log.push("FAIL " + g.id + " p" + (g.ab + 1) + " no frame with expected old text at position"); continue; }
    for (var u = 0; u < used.length; u++) if (used[u] === best && g.op === "set") { best = null; break; }
    if (!best) { fail++; log.push("FAIL " + g.id + " frame already used by another change"); continue; }
    used.push(best);
    if (nMatch > 1) log.push("NOTE " + g.id + " " + nMatch + " candidate frames, picked smallest");
    if (DRY) { ok++; log.push("MATCH " + g.id + " p" + (g.ab + 1)); continue; }
    try {
      var locked = best.locked; if (locked) best.locked = false;
      var gb0 = best.geometricBounds;
      if (g.op === "set") {
        best.contents = newS;
      } else {
        // replace substring in place, keeping the formatting of its first character
        var c = best.contents, idx = c.indexOf(oldS);
        for (var k = oldS.length - 1; k >= 1; k--) best.characters[idx + k].remove();
        if (newS.length === 0) best.characters[idx].remove(); else best.characters[idx].contents = newS;
        if (best.contents !== c.substring(0, idx) + newS + c.substring(idx + oldS.length)) throw "post-check mismatch";
      }
      var gb1 = best.geometricBounds;
      if (g.tl !== undefined) best.left += (r[0] + g.tl + (gb0[0] - (r[0] + g.x0))) - gb1[0];
      if (g.tr !== undefined) best.left += (r[0] + g.tr + (gb0[2] - (r[0] + g.x1))) - gb1[2];
      if (locked) best.locked = true;
      ok++;
    } catch (x) { fail++; log.push("FAIL " + g.id + " " + x); }
  }
  // artboard deletions last, highest index first; removes only items lying fully inside that artboard
  var dels = [];
  for (var i = 0; i < T.length; i++) if (T[i].op === "delete_artboard") dels.push(T[i]);
  dels.sort(function (p, q) { return q.ab - p.ab; });
  for (var d = 0; d < dels.length; d++) {
    var g = dels[d], r = doc.artboards[g.ab].artboardRect, items = [];
    for (var j = 0; j < doc.pageItems.length; j++) {
      var it = doc.pageItems[j]; if (it.parent.typename !== "Layer") continue; // top-level items only
      var q; try { q = it.geometricBounds; } catch (x) { continue; }
      if (q[0] >= r[0] - 1 && q[2] <= r[2] + 1 && q[1] <= r[1] + 1 && q[3] >= r[3] - 1) items.push(it);
    }
    log.push((DRY ? "WOULD DELETE " : "DELETE ") + g.id + " artboard p" + (g.ab + 1) + " top-level items=" + items.length);
    if (DRY) { ok++; continue; }
    try { for (var j = items.length - 1; j >= 0; j--) { items[j].locked = false; items[j].remove(); } doc.artboards.remove(g.ab); ok++; }
    catch (x) { fail++; log.push("FAIL " + g.id + " " + x); }
  }
  log.unshift("OK=" + ok + " FAIL=" + fail + " DRY=" + DRY + " of " + T.length);
  return log.join("\n");
}
main();
