extends: config-bases/us-single-language-base.yaml
build:
  family_id: us-es
  languages:
  - es
  web_language_block_pages:
    00_preface.rst: en
  include_lang_in_output_path: true
  word_reference_doc: docs/templates/word_template/template.docx
  word_title: '|PRODUCT_NAME| Manual de usuario'
  targets:
  - model: JE-1000F
    region: US
  - model: JE-1000E-SIL
    region: US
paths:
  page_manifest: docs/manifests/manual_us-single-es.yaml
  page_manifests:
    JE-1000E-SIL_US: docs/manifests/manual_fridgeguard_us-es.yaml
  web_illustration_manifests:
    JE-1000E-SIL_US: docs/renderers/web/je1000e_sil_us_es_illustrations.json
