extends: config-bases/eu-single-language-base.yaml

build:
  family_id: eu-en
  languages: [en]
  targets:
    - model: JE-1000F
      region: EU
    - model: JE-1000H
      region: EU
    - model: JE-2000F
      region: EU
  word_reference_doc: docs/templates/word_template/reference_en.docx
  word_title: "|PRODUCT_NAME| User Manual"
  rst_substitutions:
    MANUAL_LANGUAGE_SCOPE: English / French / Spanish / German / Italian

paths:
  page_manifest: docs/manifests/manual_eu-en.yaml
  web_illustration_manifests:
    JE-1000H_EU: docs/renderers/web/je1000h_eu_en_illustrations.json
    JE-2000F_EU: docs/renderers/web/je2000f_eu_en_illustrations.json
