extends: config-bases/eu-single-language-base.yaml

build:
  family_id: eu-es
  languages: [es]
  targets:
    - model: JE-1000F
      region: EU
    - model: JE-2000F
      region: EU
  word_title: "|PRODUCT_NAME| Manual de usuario"

paths:
  page_manifest: docs/manifests/manual_eu-single-es.yaml
  web_illustration_manifests:
    JE-2000F_EU: docs/renderers/web/je2000f_eu_es_illustrations.json
