# Generated by tools.markdown_bundle. Do not hand-edit generated output.
project = 'Jackery Battery Pack 3600 User Manual'
html_title = project
extensions = ["myst_parser"]
source_suffix = {".md": "markdown"}
root_doc = "index"
master_doc = "index"
html_theme = "furo"
exclude_patterns = ["manual_bundle.html", "_build", "Thumbs.db", ".DS_Store"]
myst_heading_anchors = 3
suppress_warnings = ["myst.header"]
html_static_path = ["_static"]
html_css_files = ["web_manual.css"]

from pathlib import Path
from shutil import copytree

def _copy_packaged_assets(app, exception):
    if exception is None:
        source = Path(app.srcdir) / "assets"
        target = Path(app.outdir) / "assets"
        copytree(source, target, dirs_exist_ok=True)

def setup(app):
    app.connect("build-finished", _copy_packaged_assets)
