from __future__ import annotations

from pathlib import Path
from typing import Any, Callable


def write_docs_root_index_for_targets(
    targets: list[Any],
    *,
    discover_existing_bundle_targets: Callable[[], list[Any]],
    bundle_dir_for_target: Callable[..., Path],
    docs_dir: Path,
) -> None:
    merged_targets: list[Any] = []
    seen: set[tuple[str | None, str | None, str | None]] = set()
    for target in [*discover_existing_bundle_targets(), *targets]:
        key = (target.model, target.region, target.lang)
        if key in seen:
            continue
        seen.add(key)
        merged_targets.append(target)

    if not merged_targets:
        return

    if len(merged_targets) == 1:
        target = merged_targets[0]
        bundle_rel = bundle_dir_for_target(
            docs_dir=docs_dir,
            model=target.model,
            region=target.region,
            lang=target.lang,
        ).relative_to(docs_dir)
        lines = [
            ".. Auto-generated by tools/build_docs.py. Do not edit directly.",
            "",
            f".. include:: {bundle_rel.as_posix()}/index",
            "",
        ]
        (docs_dir / "index.rst").write_text("\n".join(lines), encoding="utf-8")
        return

    lines = [
        "Available Manual Bundles",
        "========================",
        "",
        ".. toctree::",
        "   :maxdepth: 1",
        "",
    ]
    for target in merged_targets:
        bundle_rel = bundle_dir_for_target(
            docs_dir=docs_dir,
            model=target.model,
            region=target.region,
            lang=target.lang,
        ).relative_to(docs_dir)
        lines.append(f"   {bundle_rel.as_posix()}/index")
    lines.append("")
    (docs_dir / "index.rst").write_text("\n".join(lines), encoding="utf-8")
