from __future__ import annotations

from pathlib import Path
import re
from typing import Any, Callable

from tools.page_contracts import contract_applies_to, find_contract_for_source, load_page_contracts, required_assets_for_lang
from tools.utils.path_utils import contracts_dir_of, latex_renderer_of, static_dir_of, word_common_assets_of

_CONTRACT_TOKEN_RE = re.compile(r"\{([a-z_]+)\}")


def render_contract_asset_path(
    raw_value: str,
    *,
    model: str | None,
    region: str | None,
    lang: str | None,
) -> str:
    values = {
        "model": (model or "").strip(),
        "region": (region or "").strip(),
        "lang": (lang or "").strip(),
    }
    tokens = {match.group(1) for match in _CONTRACT_TOKEN_RE.finditer(raw_value)}
    unknown = sorted(token for token in tokens if token not in values)
    if unknown:
        raise RuntimeError(f"Unsupported contract asset token(s): {', '.join(unknown)}")
    missing = sorted(token for token in tokens if not values[token])
    if missing:
        raise RuntimeError(f"Contract asset path requires value(s) for: {', '.join(missing)}")
    return raw_value.format(**values)


def resolve_contract_asset_path(
    raw_value: str,
    *,
    docs_dir: Path,
    repo_root: Path,
    model: str | None,
    region: str | None,
    lang: str | None,
    render_contract_asset_path: Callable[..., str] = render_contract_asset_path,
) -> Path:
    rendered = render_contract_asset_path(
        raw_value,
        model=model,
        region=region,
        lang=lang,
    )
    candidate = Path(rendered)
    if candidate.is_absolute():
        return candidate

    docs_candidate = docs_dir / candidate
    if docs_candidate.exists():
        return docs_candidate
    return repo_root / candidate


def preflight_contract_assets(
    *,
    docs_dir: Path,
    repo_root: Path,
    model: str | None,
    region: str | None,
    langs: list[str],
    planned_pages: list[Any],
    bundle_dir: Path,
    source_path_for_contract: Callable[..., Path | None],
    resolve_contract_asset_path: Callable[..., Path] = resolve_contract_asset_path,
) -> None:
    contracts = load_page_contracts(contracts_dir_of(docs_dir))
    if not contracts:
        return

    seen_sources: set[tuple[str, str | None]] = set()
    for planned in planned_pages:
        page = planned.page
        page_lang = planned.lang or getattr(page, "lang", None)
        source_path = source_path_for_contract(
            page,
            docs_dir=docs_dir,
            bundle_dir=bundle_dir,
            model=model,
            region=region,
            lang=page_lang,
        )
        if source_path is None:
            continue
        source_key = (source_path.as_posix(), page_lang)
        if source_key in seen_sources:
            continue
        seen_sources.add(source_key)
        try:
            source_rel = source_path.relative_to(docs_dir).as_posix()
        except ValueError:
            source_rel = source_path.as_posix()
        contract = find_contract_for_source(source_rel, contracts)
        if contract is None:
            continue
        page_langs = [page_lang] if page_lang else langs
        for lang in page_langs:
            if not contract_applies_to(contract, lang=lang, model=model, region=region):
                continue
            for asset_path in required_assets_for_lang(contract, lang):
                resolved = resolve_contract_asset_path(
                    asset_path,
                    docs_dir=docs_dir,
                    repo_root=repo_root,
                    model=model,
                    region=region,
                    lang=lang,
                )
                if resolved.exists():
                    continue
                raise RuntimeError(
                    f"Page contract '{contract.page_id}' is missing required asset "
                    f"for lang '{lang}': {asset_path}"
                )


def write_bundle_conf_files(
    *,
    cfg: dict,
    docs_dir: Path,
    bundle_dir: Path,
    copy_file: Callable[[Path, Path], Any],
) -> tuple[Path, Path]:
    conf_base_src = docs_dir / "conf_base.py"
    if not conf_base_src.exists():
        raise RuntimeError(f"Missing conf_base.py: {conf_base_src}")

    conf_base_dst = bundle_dir / "conf_base.py"
    copy_file(conf_base_src, conf_base_dst)

    build_cfg_raw = cfg.get("build", {})
    build_cfg = build_cfg_raw if isinstance(build_cfg_raw, dict) else {}
    main_tex = str(build_cfg.get("main_tex", "manual_demo.tex"))

    conf_text = "\n".join(
        [
            "# Auto-generated by tools/gen_index_bundle.py",
            "# -*- coding: utf-8 -*-",
            "",
            "import sys",
            "from pathlib import Path",
            "",
            "THIS_DIR = Path(__file__).resolve().parent",
            "if str(THIS_DIR) not in sys.path:",
            "    sys.path.insert(0, str(THIS_DIR))",
            "",
            "from conf_base import *  # noqa: F403",
            "",
            "master_doc = 'index'",
            "exclude_patterns = ['_build', 'page/*', 'generated/*', 'generated/**/*']",
            "html_static_path = ['_static']",
            "html_extra_path = ['renderers/latex/assets']",
            f"latex_documents = [('index', '{main_tex}', '', '', 'howto')]",
            "latex_domain_indices = False",
            "",
        ]
    )
    conf_dst = bundle_dir / "conf.py"
    conf_dst.write_text(conf_text, encoding="utf-8")
    return conf_dst, conf_base_dst


def copy_bundle_support_assets(
    *,
    docs_dir: Path,
    bundle_dir: Path,
    copytree_replace: Callable[[Path, Path], None],
) -> None:
    static_src = static_dir_of(docs_dir)
    if static_src.exists():
        copytree_replace(static_src, static_dir_of(bundle_dir))

    latex_src = latex_renderer_of(docs_dir)
    if latex_src.exists():
        copytree_replace(latex_src, latex_renderer_of(bundle_dir))

    common_assets_src = word_common_assets_of(docs_dir)
    if common_assets_src.exists():
        copytree_replace(
            common_assets_src,
            bundle_dir / "_assets" / "templates" / "word_template" / "common_assets",
        )


def build_bundle_manifest(
    *,
    model: str | None,
    region: str | None,
    lang: str | None,
    page_manifest_path: Path | None,
    spec_master_csv: Path,
    page_paths: list[Path],
    generated_dir: Path,
    recipe_ids: list[str],
    snippet_ids: list[str],
    repo_root: Path,
    repo_relative: Callable[[Path | None], str | None],
    file_sha256: Callable[[Path | None], str | None],
) -> dict[str, object]:
    return {
        "model": model,
        "region": region,
        "lang": lang,
        "page_manifest": repo_relative(page_manifest_path),
        "spec_master": {
            "path": repo_relative(spec_master_csv),
            "sha256": file_sha256(spec_master_csv),
        },
        "recipe_ids": list(dict.fromkeys(recipe_ids)),
        "snippet_ids": list(dict.fromkeys(snippet_ids)),
        "page_files": [repo_relative(path) for path in page_paths],
        "generated_files": [
            repo_relative(path)
            for path in sorted(path for path in generated_dir.rglob("*.rst") if path.is_file())
        ],
    }
