#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from __future__ import annotations

import os
import re
import subprocess
from pathlib import Path
from urllib.parse import unquote, urlparse

from tools.gen_index_bundle import MaterializedBundle
from tools.word_bundle_common import paths
from tools.word_bundle_docx_pandoc import resolve_pandoc_binary
from tools.word_bundle_html import build_word_bundle_html


MYST_COMPATIBLE_WRITER = "commonmark_x+pipe_tables+yaml_metadata_block-fenced_divs-bracketed_spans-attributes"
_FILE_URI_RE = re.compile(r"file:///[^\s\"')<>]+")


def resolve_markdown_writer(pandoc_bin: str) -> str:
    proc = subprocess.run(
        [pandoc_bin, "--list-output-formats"],
        check=True,
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    formats = {line.strip() for line in proc.stdout.splitlines() if line.strip()}
    if "myst" in formats:
        return "myst"
    if "commonmark_x" in formats:
        return MYST_COMPATIBLE_WRITER
    if "gfm" in formats:
        return "gfm"
    return "markdown"


def _rewrite_local_file_uris_to_relative(markdown_path: Path) -> None:
    base_dir = markdown_path.parent.resolve()
    text = markdown_path.read_text(encoding="utf-8")

    def local_path_from_uri(raw_uri: str) -> Path:
        parsed = urlparse(raw_uri)
        path_text = unquote(parsed.path)
        if os.name == "nt" and re.match(r"^/[A-Za-z]:", path_text):
            path_text = path_text[1:]
        return Path(path_text).resolve()

    def replace(match: re.Match[str]) -> str:
        raw_uri = match.group(0)
        parsed = urlparse(raw_uri)
        if parsed.scheme.lower() != "file":
            return raw_uri
        local_path = local_path_from_uri(raw_uri)
        try:
            relative_path = local_path.relative_to(base_dir)
        except ValueError:
            return raw_uri
        return relative_path.as_posix()

    rewritten = _FILE_URI_RE.sub(replace, text)
    if rewritten != text:
        markdown_path.write_text(rewritten, encoding="utf-8")


def _write_myst_sphinx_scaffold(markdown_path: Path, *, title: str) -> None:
    source_dir = markdown_path.parent
    source_dir.mkdir(parents=True, exist_ok=True)
    project_title = title.strip() or "Manual"
    conf_path = source_dir / "conf.py"
    conf_path.write_text(
        "\n".join(
            [
                "# Generated by tools.markdown_bundle. Do not hand-edit generated output.",
                f"project = {project_title!r}",
                "html_title = project",
                'extensions = ["myst_parser"]',
                'source_suffix = {".md": "markdown"}',
                'root_doc = "index"',
                'master_doc = "index"',
                'html_theme = "furo"',
                'exclude_patterns = ["manual_bundle.html", "_build", "Thumbs.db", ".DS_Store"]',
                "myst_heading_anchors = 3",
                'suppress_warnings = ["myst.header"]',
                "",
            ]
        ),
        encoding="utf-8",
    )
    if markdown_path.name == "index.md":
        return

    manual_ref = markdown_path.with_suffix("").name
    index_path = source_dir / "index.md"
    index_path.write_text(
        "\n".join(
            [
                f"# {project_title}",
                "",
                "```{toctree}",
                ":maxdepth: 2",
                "",
                manual_ref,
                "```",
                "",
            ]
        ),
        encoding="utf-8",
    )


def export_markdown_from_bundle(
    cfg: dict,
    model: str | None,
    region: str | None,
    markdown_output: str,
    *,
    materialized_bundle: MaterializedBundle | None = None,
    output_dir: Path | None = None,
) -> Path:
    bundle_output_dir = output_dir
    bundle_html, _reference_doc, _page_metas = build_word_bundle_html(
        cfg,
        model,
        region,
        materialized_bundle=materialized_bundle,
        output_dir=bundle_output_dir,
    )

    out_path = Path(markdown_output)
    if not out_path.is_absolute():
        out_root = bundle_output_dir or (paths.docs_build_dir / "md")
        out_path = out_root / out_path
    out_path.parent.mkdir(parents=True, exist_ok=True)

    resource_path = os.pathsep.join(
        [
            str(bundle_html.parent),
            str(paths.docs_dir),
            str(paths.root),
        ]
    )
    pandoc_bin = resolve_pandoc_binary(None)
    markdown_writer = resolve_markdown_writer(pandoc_bin)
    markdown_reader = "html" if markdown_writer == "myst" else "html-native_divs-native_spans"
    subprocess.run(
        [
            pandoc_bin,
            str(bundle_html),
            f"--from={markdown_reader}",
            f"--to={markdown_writer}",
            "--markdown-headings=atx",
            "--wrap=none",
            "--resource-path",
            resource_path,
            "-o",
            str(out_path),
        ],
        check=True,
        cwd=str(paths.root),
    )
    _rewrite_local_file_uris_to_relative(out_path)
    bundle_title = materialized_bundle.title if materialized_bundle is not None else "Manual"
    _write_myst_sphinx_scaffold(out_path, title=bundle_title)
    return out_path
